### ISSUE TITLE
Git credentials stopped working after updating Visual Studio Online extension to 1.0.2081

### ISSUE THREAD

**Issue by dbanisimov** [MicrosoftDocs/codespaces#435]
I'm using a cloud-hosted VS Online environment and connecting to it from VS Code. Git credentials stopped working in the remote environment a few days ago - both GUI and CLI git ask for username and password every time for my https remotes.

After downgrading the extension version I found out that the last working version was 1.0.1968, after that 1.0.2081 and 1.0.2096 both have the issue with git credentials.

I have no problems when using VS Online from the browser, also my local git installation is using wincred credentials helper without any problems.

**Comment by jkeech** [comment]
@edgonmsft, can you take a look?

**Comment by edgonmsft** [comment]
Hi Denis!

I'm taking a look. I just have a couple of quiestions:

- How old is this environment?
- Can you run the following command and tell me the output? `git config credential.helper`
- As a quick test, does the same happen to you in a new environment?

Thanks!

**Comment by edgonmsft** [comment]
By the way, can you run the command both inside and outside the environment?

**Comment by dbanisimov** [comment]
Hi Edmundo!

The environment was created on March 11, 2020 5:01 PM
`git config credential.helper` >> `/.vsonline/bin/vso gitCredential`
Outside the environment >> `wincred`

The issue does happen to me in a new environment.  But with a twist.

1.  I created a brand new environment without linking a repo and did `git clone` in the environment connected from VS Code on my local machine. It **didn't ask** for username/password.

2. Then, I suspended the environment and connected to it again. This time `git pull` asked me for credentials. The same issue.

3. Downgrading the extension helped here again. Git credentials were working as expected. Updating it back to the latest - credentials are not

The issue didn't happen initially in an older environment created on November 20, 2019 that I haven't used for a few weeks. Git credentials worked there correctly the first time, even on the latest version, but on the second connection the same issue appeared. Apart from the creation date, that env also differs in the way that the repo was cloned at the env creation (I see 'Repository' line on that env in the list of environments). In the two new environments git repo was cloned manually after the creation.

To test whether it somehow related to the way you initialize and clone the environment I created a new environment again, this time specifying the repo on creation. It cloned succesfully, worked after 1 suspend-connect cycle, but stoped working the next time.

All environments are in westus2

**Comment by edgonmsft** [comment]
Hi Denis!

Thanks a lot for the really detailed report!

I'm trying to reproduce your issue. 

One additional question I forgot the first time. Do you also use VSO Web to connect to the environment? We have an issue where if you connect to the environment from both the credential proxy only works to the first of them and in some cases might not work till after some time.

Might this be related in your case?

To confirm, you mentioned it works fine for you from the Web right?

Thanks a lot!

**Comment by dbanisimov** [comment]
It works on VSO web well. I don't usually use VSO web, and I've only checked on it while trying to figure out the cause of the initial issue.

But after your comment to rule out VSO web out of the equation I created a new environment using VS Code extension without a repo configured and connected to it right away using VS Code. The first `git clone` after the first connection worked fine. I suspended the environment, connected to it via VS Code again and `git pull` didn't work - asks for username/password. Note that VSO web had never launched so far.

**Comment by dbanisimov** [comment]
I've also discovered that my Azure payment was past due because of the expired card. But as far as I can tell from the portal the subscription and all resources were still active. I've fixed the payment, but the issue is still here. I will also double check later in case it fixes itself with a delay.

**Comment by dbanisimov** [comment]
Seems like it got fixed in the latest insiders build (I've got an update installed overnight). When I connected to the environment and did `git pull` a popup window saying "The extension 'Git' wants to sign in using GitHub" appeared. After authorizing on the GitHub page it took me back to VS Code and now git credentials seem to work as expected.

It looks like it's still not using my local machine `wincred` helper, as it already had the personal token saved and shouldn't have asked, but at least it saves the credentials somewhere.

The stable VS Code channel still has the original issue.

**Comment by edgonmsft** [comment]
Hi Denis!

That's interesting and gives me more information to reproduce your issue.

Let me try the same.

**Comment by haodeon** [comment]
I'm encountering the same problem. I first thought it was something broken in my environment so I created a new environment on both US west 2 and SE Asia. Both times I encountered this problem. Then I found this issue and tried downgrading to previous version and it resolved the issue for me.

**Comment by edgonmsft** [comment]
Hi!
We have identified the issue and are testing a fix for it. 

I'll post here when the fix is released.

**Comment by osortega** [comment]
@dbanisimov @haodeon the fix should already be deployed.
Feel free to reopen the issue if you are still seeing this issue.

Thanks for reporting this
